apiVersion: v1
kind: Pod
metadata:
  name: data-uploader
spec:
  restartPolicy: Never
  containers:
  - name: uploader
    image: ubuntu:22.04
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    volumeMounts:
    - name: slt-data
      mountPath: /data
  volumes:
  - name: slt-data
    persistentVolumeClaim:
      claimName: slt-data
